// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFirstApp.Data;

#nullable disable

namespace MyFirstApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818193835_SeedProjectData")]
    partial class SeedProjectData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyFirstApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "WEB DEVELOPMENT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DESKTOP DEVELOPMENT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MOBILE DEVELOPMENT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ARTIFICIAL INTELLIGENCE"
                        });
                });

            modelBuilder.Entity("MyFirstApp.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TechnologiesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "ASP.NET CORE MVC PROJECT",
                            GitHubUrl = "https://github.com/example/my-first-app",
                            IsPublic = true,
                            License = "MIT",
                            Name = "MY FIRST APP",
                            ProjectType = "WEB",
                            TechnologiesCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "NOTE MANAGEMENT APPLICATION",
                            GitHubUrl = "https://github.com/example/notes-app",
                            IsPublic = true,
                            License = "MIT",
                            Name = "NOTES APP",
                            ProjectType = "WEB",
                            TechnologiesCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "AI BASED SMART SYSTEM",
                            GitHubUrl = "https://github.com/example/smart-system",
                            IsPublic = true,
                            License = "MIT",
                            Name = "SMART SYSTEM",
                            ProjectType = "AI",
                            TechnologiesCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "CROSS PLATFORM MOBILE APPLICATION",
                            GitHubUrl = "https://github.com/example/mobile-app",
                            IsPublic = false,
                            License = "MIT",
                            Name = "MOBILE APP",
                            ProjectType = "MOBILE",
                            TechnologiesCount = 0
                        });
                });

            modelBuilder.Entity("MyFirstApp.Models.ProjectDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Client")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 1000m,
                            Client = "CLIENT A",
                            EndDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Budget = 1500m,
                            Client = "CLIENT B",
                            EndDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2,
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Budget = 3000m,
                            Client = "CLIENT C",
                            EndDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 3,
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Budget = 2000m,
                            Client = "CLIENT D",
                            EndDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 4,
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MyFirstApp.Models.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ASP.NET CORE"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MYSQL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JAVASCRIPT"
                        },
                        new
                        {
                            Id = 5,
                            Name = "PYTHON"
                        },
                        new
                        {
                            Id = 6,
                            Name = "FLUTTER"
                        });
                });

            modelBuilder.Entity("ProjectTechnology", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologiesId")
                        .HasColumnType("int");

                    b.HasKey("ProjectsId", "TechnologiesId");

                    b.HasIndex("TechnologiesId");

                    b.ToTable("ProjectTechnology", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectsId = 1,
                            TechnologiesId = 1
                        },
                        new
                        {
                            ProjectsId = 1,
                            TechnologiesId = 2
                        },
                        new
                        {
                            ProjectsId = 1,
                            TechnologiesId = 3
                        },
                        new
                        {
                            ProjectsId = 2,
                            TechnologiesId = 1
                        },
                        new
                        {
                            ProjectsId = 2,
                            TechnologiesId = 2
                        },
                        new
                        {
                            ProjectsId = 2,
                            TechnologiesId = 3
                        },
                        new
                        {
                            ProjectsId = 3,
                            TechnologiesId = 5
                        },
                        new
                        {
                            ProjectsId = 3,
                            TechnologiesId = 3
                        },
                        new
                        {
                            ProjectsId = 4,
                            TechnologiesId = 6
                        },
                        new
                        {
                            ProjectsId = 4,
                            TechnologiesId = 4
                        });
                });

            modelBuilder.Entity("MyFirstApp.Models.Project", b =>
                {
                    b.HasOne("MyFirstApp.Models.Category", "Category")
                        .WithMany("Projects")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyFirstApp.Models.ProjectDetails", b =>
                {
                    b.HasOne("MyFirstApp.Models.Project", "Project")
                        .WithOne("ProjectDetails")
                        .HasForeignKey("MyFirstApp.Models.ProjectDetails", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectTechnology", b =>
                {
                    b.HasOne("MyFirstApp.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFirstApp.Models.Technology", null)
                        .WithMany()
                        .HasForeignKey("TechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyFirstApp.Models.Category", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("MyFirstApp.Models.Project", b =>
                {
                    b.Navigation("ProjectDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
